### ISSUE TITLE
Not loading on Roku

### ISSUE THREAD

**Issue by rkdavis7** [pranav-prakash/RokuCast#11]
Hi, thank you for a great app. I'm trying to get it working on my Roku 3. It appears to start loading on the private channel app and then disappears. I would love to get this working for my baby boy. Thank you

Player: http://www.tg4.ie/ga/player/gasuir/
Chrome Version 53.0.2785.89 beta-m (64-bit)

**Comment by pranav-prakash** [comment]
Ok it seems that website uses the [blob](https://stackoverflow.com/questions/14952052/convert-blob-url-to-normal-url) method of playback through the new chrome media stream api. That is, the content is fetched from the server, cached by the browser, and the video element points to the cached segment in the browser.

The quickest workaround is to change the useragent to a mobile device. Use [this](https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg/related?hl=en-US) extension, and on the tg4.ie open the extension, the android dropdown, and select *Android KitKat*. Refresh afterwards.

If it works, then you can add the website to the permanent spoof list in extension options to avoid having to switch back and forth between useragents.

**Comment by rkdavis7** [comment]
Wow, that worked perfectly. Thank you very much for taking the time to
reply and write this app! Have a great day. Ross
