### ISSUE TITLE
Error in Chrome on Install

### ISSUE THREAD

**Issue by sosebee** [pranav-prakash/RokuCast#12]
I unpacked the folder, enabled developer mode, and added the RokuCast extension.  I immediately get an error and when I try to use the extension to cast to my Roku, it just tells me that there is no video on the page. 

Error:
Refused to load the script 'https://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' because it violates the following Content Security Policy directive: "script-src 'self' http://localhost:9008 https://www.google-analytics.com".

**Comment by pranav-prakash** [comment]
Which website are you using it on?

**Comment by sosebee** [comment]
I have tried several.  It worked on one sample file so far.  I think I have found the problem after m]a little digging.  It looks like it does not work with sites that are still embedding their videos with flash but build the site with HTML5.  Weird that they would still be doing that.  Any updates coming to all for additional content formats like flash?

**Comment by pranav-prakash** [comment]
Yeah I noted that near the bottom of the README file.

It's a lot harder to find the source video url when using embedded flash players; plus flash players often have some sort of additional DRM.

It *might* be possible to find it using chrome's network request monitoring however. I'll have to look into that.

As a side note most websites also have a mobile version that defaults to an HTML5 player. Try setting your useragent to be a mobile device (using [this](https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg/related) for example) and see if you get an HTML5 version.

**Comment by sosebee** [comment]
I will give the extension a try.  Thank you for the app and Thank you for the advice!!!

**Comment by nathanstuart01** [comment]
Posted my flash issue in another thread, my bad. Saw your user agent suggestion and it works like a charm, this is legit!! Thanks for making and sharing it.
