### ISSUE TITLE
Add context menu?

### ISSUE THREAD

**Issue by ph0rn** [pranav-prakash/RokuCast#16]
Any chance you could add a context menu to links?
For example if a page has a hyperlink to an .mp4 file, you could right click the link, and select an option to cast. As opposed to the extension only detecting embedded video tags on the page

**Comment by ph0rn** [comment]
made pull request #17 for this

**Comment by pranav-prakash** [comment]
Cool nice idea. I've gone ahead and merged it in. 

Thanks!
