### ISSUE TITLE
403 Forbidden while fetching file from server

### ISSUE THREAD

**Issue by Jhanbhaia** [pranav-prakash/RokuCast#18]
Hi, every time I try casting a video I get the error in the header above. Tried uninstalling/reinstalling app and extension.

**Comment by pranav-prakash** [comment]
What video are you trying to cast?

**Comment by Jhanbhaia** [comment]
Any video from Youtube or this site: https://www.arconaitv.me/koth/

**Comment by pranav-prakash** [comment]
See: https://github.com/pranav-prakash/RokuCast/issues/14 for the YouTube issue.

I'm still investigating into the arconaitv issue. For some reason when roku requests the m3u8 file it gets a 403 forbidden error, while fetching the file from desktop works fine. Perhaps the server is blocking based on user-agent or headers or something. I'll dig a bit deeper and see.

**Comment by pranav-prakash** [comment]
Ok confirmed: the server filters requests based on the user agent. If the user agent header has the word "roku" in it, we get back a 403. This is relatively simple to fix, but you'll have to use the branch that has a separate receiver app (the playOnRoku branch will not work).
