### ISSUE TITLE
How do you install? Where is the executable file?

### ISSUE THREAD

**Issue by DanielitoXYZ** [pranav-prakash/RokuCast#19]
How do you install RokuCast? I don't see any executable file when I download the files. Do you copy them somewhere instead? And if not then what should I run? Thanks!

**Comment by pranav-prakash** [comment]
Sorry I forgot to update the installation instructions when I created the new branch. I added them to the readme now. 

> 
> First download the [zip](https://github.com/pranav-prakash/RokuCast/archive/playOnRoku.zip) file of the repo and unzip it on to the desktop:
> 
> In Chrome navigate to preferences -> extensions and enable "developer mode" by clicking on the upper-right checkbox.
> 
> Then click "Load Unpacked Extension" and browse to the folder called RokuCast in the unzipped archive.

The chrome extension is all you need. Then follow the instructions in the usage section of the readme to enter your Roku's ip address.
