### ISSUE TITLE
New update required

### ISSUE THREAD

**Issue by Amandysha** [pranav-prakash/RokuCast#2]
Congratulations by this great idea, unique. Thank you! This extension no longer works? I try but not work on two PC's with Windows 10 and Chrome version 47.0.2526.106 m. Try with two Roku's: Roku LT and Roku 1 version 7.0 build 9044.

**Comment by pranav-prakash** [comment]
Thanks for the kind words!

It still seems to work for me — which website are you trying it on?

**Comment by Amandysha** [comment]
Many thanks for the prompt reply! I try with this video https://people.mozilla.org/~mfinkle/casting/test.html and this: http://camendesign.com/code/video_for_everybody/test.html

**Comment by pranav-prakash** [comment]
Yeah those seem to work fine for me. What is the issue you are facing?

You are only casting the .mp4 versions of the videos right? And I assume you've entered your Roku's IP address in the settings menu and also installed the receiver app on your roku?

**Comment by Amandysha** [comment]
Yeah! Specifically try casting video .mp4. Also, I entered my Roku IP in the settings menu on extension and also install the RokuCast receiver app on my roku.
The problem is because Roku App opened and try play video but closes immediately. 

Sure you tried with the last Roku 7.0 updated build 9044?

**Comment by pranav-prakash** [comment]
Hm I think I might know what's going on. 

How did you install the chrome extension? Did you get the .zip from the release page, directly by cloning the repo, or use the .crx file?

And you installed the receiver app through development mode in roku right?

Depending on how you installed the chrome extension, the id of the app trying to be launched may be different from what is installed on the roku.

Try installing the private channel version of the receiver app: http://owner.roku.com/add/RM5R2N

The development mode app has a different id from the private-channel version one that is found in some of the chrome extensions.

**Comment by Amandysha** [comment]
I get the .zip with extension and RokuCast receiver app from here: https://github.com/pranav-prakash/RokuCast/archive/master.zip. Btw, I can't install you private roku channel. Roku Store says: "The channel code provided is not associated with a valid channel".

**Comment by pranav-prakash** [comment]
Sorry I forgot to enable the private channel for other countries. Try with this one:

https://owner.roku.com/add/RM5R2N

**Comment by Amandysha** [comment]
"This channel cannot be added". Please, see: http://i.imgur.com/iLUjuln.jpg

**Comment by pranav-prakash** [comment]
My bad again. Try this:

https://owner.roku.com/add/5QZQVQ

**Comment by Amandysha** [comment]
Thanks! I finally install. But something strange happens, my Roku not display the new added channel. I update my Roku and not shows this new channel to install.

**Comment by pranav-prakash** [comment]
Hmm..

What method did you use to install the chrome extension? Did you use the extension file (.crx) method or use the unpacked extension?

Could you go to:

http://[ROKU IP HERE]:8060/query/apps

(where [ROKU IP HERE] is replaced by the IP of your roku, for instance http://10.0.1.40:8060/query/apps)

in your browser and tell me the app id it shows for RokuCast? it should give something like:

`<app id="59310" type="appl" version="0.0.0">RokuCast</app>`

**Comment by Amandysha** [comment]
Last night removed and reinstalled chrome extension. Download from here ( (https://github.com/pranav-prakash/RokuCast/releases) and install like a unpacked extension. 
 
Btw, **my App ID**: <app id="59310" type="appl" version="0.0.0">RokuCast</app>

**Comment by pranav-prakash** [comment]
Ok good. Let's try to cast a url to the roku manually.

Can you go to this webpage:

http://people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4

Then open the developer console (Cmd + Opt + J if on a mac, Ctrl + Shift + J if on a PC).

Then paste in 

    var url = "http://[ROKU IP HERE]:8060/launch/59310?version=1&url=https%3A%2F%2Fpeople.mozilla.org%2F~mfinkle%2Fcasting%2FMozilla_Firefox_Manifesto_v0.2_640.mp4&title=https%3A%2F%2Fpeople.mozilla.org%2F~mfinkle%2Fcasting%2FMozilla_Firefox_Manifesto_v0.2_640.mp4&image=undefined";

    var method = "POST";
    var postData = "";
    var async = true;

    var request = new XMLHttpRequest();
    request.open(method, url, async);
    request.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
    request.send(postData);


into the javascript console, where [ROKU IP HERE] is again replaced by the IP address of your roku.


If it works, the video should begin playing.

**Comment by Amandysha** [comment]
Sorry, nothing happens. I tried several times but still App opened on Roku and tried play the video but closes immediately. See image about: http://i.imgur.com/3Eis30n.png

**Comment by pranav-prakash** [comment]
Hmm..

The issue might be on the receiver app side then. We can try debugging based on what the roku receives.

To do this you will need to go back to the roku app installed by uploading the "RokuCast Receiver.zip" in development mode (like you did originally).

And for the chrome extension, install unpacked extension from: https://github.com/pranav-prakash/RokuCast/releases/download/1.1/RokuCast-Chrome-Dev.zip

Do you know how to use telnet? 

From command prompt/terminal type 

    telnet [ROKU IP] 8080
 
and it should give something like:

    Trying 10.0.1.36...
    Connected to 10.0.1.36.
    Escape character is '^]'.

Then try casting the video. It will display debugging information, and hopefully give the reason for the crash.

**Comment by Amandysha** [comment]
`------ Running dev 'RokuCast' main ------
launch params: splashTime: 1600
source: auto-run-dev
instant_on_run_mode: foreground
lastExitOrTerminationReason: EXIT_UNKNOWN

show main screen

------ Running dev 'RokuCast' main ------
launch params: splashTime: 1600
source: external-control
version: 1
image: undefined
instant_on_run_mode: foreground
url: http://people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
title: people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
lastExitOrTerminationReason: EXIT_UNKNOWN

http://people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
undefined
[{"description": "people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4","url": "http://people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4","title": "people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4","poster": "undefined"}]
Displaying video:
srt =
play failed:

------ Running dev 'RokuCast' main ------
launch params: splashTime: 1600
source: external-control
version: 1
image: undefined
instant_on_run_mode: foreground
url: http://people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
title: people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
lastExitOrTerminationReason: EXIT_UNKNOWN

http://people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
undefined
[{"description": "people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4","url": "http://people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4","title": "people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4","poster": "undefined"}]
Displaying video:
srt =
play failed:

------ Running dev 'RokuCast' main ------
launch params: splashTime: 1600
source: external-control
version: 1
image: undefined
instant_on_run_mode: foreground
url: http://people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
title: people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
lastExitOrTerminationReason: EXIT_UNKNOWN

http://people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
undefined
[{"description": "people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4","url": "http://people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4","title": "people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4","poster": "undefined"}]
Displaying video:
srt =
play failed:`

**Comment by pranav-prakash** [comment]
Ahh I think I might have found the issue

Can you try using this new receiver app on the roku (upload via dev mode)?

If it still does not work, can you run a speedtest from your roku and tell me the Mbps you are getting?

[NewRokuCastReceiver.zip](https://github.com/pranav-prakash/RokuCast/files/72917/NewRokuCastReceiver.zip)

**Comment by Amandysha** [comment]
Still App opened on Roku and tried play the video but closes immediately. :cry: Btw, Speedtest: 5190 Mbits/s

**Comment by pranav-prakash** [comment]
Try this version:

[testv2.zip](https://github.com/pranav-prakash/RokuCast/files/72948/testv2.zip)

**Comment by pranav-prakash** [comment]
Hm can you try this one?

If it crashes, can you `telnet` again to roku and paste output?

[Archive.zip](https://github.com/pranav-prakash/RokuCast/files/72949/Archive.zip)

**Comment by Amandysha** [comment]
Okey! 

------ Running dev 'RokuCast' main ------
launch params: splashTime: 1600
source: external-control
version: 1
image: https://people.mozilla.org/favicon.ico
instant_on_run_mode: foreground
url: https://people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
title: Video Casting Test
lastExitOrTerminationReason: EXIT_UNKNOWN

https://people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
Video Casting Test
https://people.mozilla.org/favicon.ico
[{"description": "people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4","url": "http://people.mozi
lla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4","title": "people.mozilla.org/~mfinkle/casting/Mozilla_F
irefox_Manifesto_v0.2_640.mp4","poster": "undefined"},{"description": "Video Casting Test","url": "https://people.mozill
a.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4","title": "Video Casting Test","poster": "https://people.m
ozilla.org/favicon.ico"},{"description": "Video Casting Test","url": "https://people.mozilla.org/~mfinkle/casting/Mobile
-launch-greatday640.mp4","title": "Video Casting Test","poster": "https://people.mozilla.org/favicon.ico"}]
Displaying video:
srt =
switchingstrategy: full-adaptation
streamformat: mp4
streamurls: <Component: roArray>
streamqualities: <Component: roArray>
streambitrates: <Component: roArray>
title: <Component: roArray>

play failed: -5

**Comment by pranav-prakash** [comment]
Hm, according to Roku the code of -5 for play failed seems to mean:

>Media error; the media format is unknown or unsupported

I noticed in your debug output that it showed the following as empty

    switchingstrategy: full-adaptation
    streamformat: mp4
    streamurls: 
    streamqualities: 
    streambitrates: 
    title:

In my debug output it shows like 

    switchingstrategy: full-adaptation
    streamformat: mp4
    streamurls: <Component: roArray>
    streamqualities: <Component: roArray>
    streambitrates: <Component: roArray>
    title: <Component: roArray>

This might be the root cause, though I am not sure why it happens. Can you post the `telnet` output after installing this app:

[Uploading ArchiveNew.zip…]()

**Comment by Amandysha** [comment]
No, is not empty, is that Github hide the code when I paste here. See image about: http://i.imgur.com/uiFgLYc.png


**Btw, again app crash**: 

------ Running dev 'RokuCast' main ------
launch params: splashTime: 1600
source: external-control
version: 1
image: undefined
instant_on_run_mode: foreground
url: http://people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
title: people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
lastExitOrTerminationReason: EXIT_UNKNOWN

http://people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
undefined
[{"description": "people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4","url": "http://people.mozi
lla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4","title": "people.mozilla.org/~mfinkle/casting/Mozilla_F
irefox_Manifesto_v0.2_640.mp4","poster": "undefined"},{"description": "Video Casting Test","url": "https://people.mozill
a.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4","title": "Video Casting Test","poster": "https://people.m
ozilla.org/favicon.ico"},{"description": "Video Casting Test","url": "https://people.mozilla.org/~mfinkle/casting/Mobile
-launch-greatday640.mp4","title": "Video Casting Test","poster": "https://people.mozilla.org/favicon.ico"}]
Displaying video:
url: http://people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
title: people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4
poster: undefined

false
srt =
switchingstrategy: full-adaptation
streamformat: mp4
streamurls: <Component: roArray>
streamqualities: <Component: roArray>
streambitrates: <Component: roArray>
title: <Component: roArray>

http://people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4

HD

 0

mp4
people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4

play failed: -5

**Comment by pranav-prakash** [comment]
Is it still crashing immediately or do you see the "buffering" screen for a while before it crashes?

And can you try casting this webpage: http://camendesign.com/code/video_for_everybody/test.html

**Comment by Amandysha** [comment]
First, the app open and display "loading", then when try to upload the video start "retriever" but immediately close.


**Telnet**: 

------ Running dev 'RokuCast' main ------
launch params: splashTime: 1600
source: external-control
version: 1
image: http://camendesign.com/favicon.ico
instant_on_run_mode: foreground
url: http://clips.vorwaerts-gmbh.de/VfE_html5.mp4
title:  Ç Video For Everybody Ç  Test Page
lastExitOrTerminationReason: EXIT_UNKNOWN

http://clips.vorwaerts-gmbh.de/VfE_html5.mp4
 Ç Video For Everybody Ç  Test Page
http://camendesign.com/favicon.ico
[{"description": "people.mozilla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4","url": "http://people.mozi
lla.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4","title": "people.mozilla.org/~mfinkle/casting/Mozilla_F
irefox_Manifesto_v0.2_640.mp4","poster": "undefined"},{"description": "Video Casting Test","url": "https://people.mozill
a.org/~mfinkle/casting/Mozilla_Firefox_Manifesto_v0.2_640.mp4","title": "Video Casting Test","poster": "https://people.m
ozilla.org/favicon.ico"},{"description": "Video Casting Test","url": "https://people.mozilla.org/~mfinkle/casting/Mobile
-launch-greatday640.mp4","title": "Video Casting Test","poster": "https://people.mozilla.org/favicon.ico"},{"description
": " Ç Video For Everybody Ç  Test Page","url": "http://clips.vorwaerts-gmbh.de/VfE_html5.mp4","title": " Ç Video For Ev
erybody Ç  Test Page","poster": "http://camendesign.com/favicon.ico"},{"description": " Ç Video For Everybody Ç  Test Pa
ge","url": "http://clips.vorwaerts-gmbh.de/VfE.webm","title": " Ç Video For Everybody Ç  Test Page","poster": "http://ca
mendesign.com/favicon.ico"},{"description": "Me han pillado - YouTube","url": "blob:https%3A//www.youtube.com/7a81e6d8-8
28f-4a82-9c1a-d3747217ca80","title": "Me han pillado - YouTube","poster": "https://s.ytimg.com/yts/img/favicon-vflz7uhzw
.ico"}]
Displaying video:
url: http://clips.vorwaerts-gmbh.de/VfE_html5.mp4
title:  Ç Video For Everybody Ç  Test Page
poster: http://camendesign.com/favicon.ico

false
srt =
switchingstrategy: full-adaptation
streamformat: mp4
streamurls: <Component: roArray>
streamqualities: <Component: roArray>
streambitrates: <Component: roArray>
title: <Component: roArray>

http://clips.vorwaerts-gmbh.de/VfE_html5.mp4

HD

 0

mp4
 Ç Video For Everybody Ç  Test Page

play failed: -5

**Comment by Amandysha** [comment]
I have a SD TV.

**Comment by Amandysha** [comment]
On my iOS device I use two Apps to send videos from the browser to the Roku Player: [TV Cast R] (https://itunes.apple.com/us/app/video-tv-cast-for-roku-best/id969086312?mt=8) and [Rocket Roku Cast] (https://itunes.apple.com/us/app/rocket-video-cast-for-roku/id357555848?mt=8). Both Apps work good without any problem.

**Comment by pranav-prakash** [comment]
I think I have fixed it now! The problem was with my app — I set all streams as HD quality, but since you have an SD TV the Roku did not know what to do and it quit.

Now I have added an SD stream so the Roku can automatically pick the right one based on the tv type.

Please try:

[Archive3.zip](https://github.com/pranav-prakash/RokuCast/files/73670/Archive3.zip)

**Comment by Amandysha** [comment]
:smiley: :smiley: :smiley: Yes! Yes! Yes! Now works! You rock! You are the best and friendliest developer in the world!!! Thank you so much for helping me!!

Btw, you will update you private [Roku channel] (https://owner.roku.com/add/5QZQVQ) with this new version [Archive3] (https://github.com/pranav-prakash/RokuCast/files/73670/Archive3.zip)?

**Comment by pranav-prakash** [comment]
Done :smile:

https://my.roku.com/add/CL9D5D
