### ISSUE TITLE
Installing in Developer Mode

### ISSUE THREAD

**Issue by crystal90** [pranav-prakash/RokuCast#21]
I'm trying to use your extension with chrome but chrome keeps disabling rokucast. this is the message:

Which extensions you can use on Chrome
To protect you while you browse, Chrome only lets you use extensions that have been published on the Chrome Web Store.
If you need to use a disabled extension, you can contact the extension’s developer and ask them to upload their extension to the Chrome Web Store. This will allow you, and other people who use Chrome, to install that extension from the Chrome Web Store, or if you already have it installed, to manually re-enable it from your list of extensions.

can you fix this?

I'm using roku premiere 4620x v 7.51 build 4095-29  
chrome  version 56.0.2924.87 (64-bit)

**Comment by pranav-prakash** [comment]
Are you installing the unpacked chrome extension in developer mode?

>First download the [zip file](https://github.com/pranav-prakash/RokuCast/archive/playOnRoku.zip) of the repo and unzip it on to the desktop:

>In Chrome navigate to preferences -> extensions and enable "developer mode" by clicking on the upper-right checkbox.

>Then click "Load Unpacked Extension" and browse to the folder called RokuCast in the unzipped archive.

**Comment by crystal90** [comment]
I followed your instructions and chrome has not disabled the extension.
However, I cannot get the video to connect to my roku.
I added the roku ip to rokucast. I start playing the video and when I click
on rokucast icon I get this message. I've tried reloading the video but it
won't work.

no video detected then it shows:
HTML5 Video
&app=explorer&xmi=44.mp4

Is it possible that the format is not acceptable to rokucast. I was hoping
to use this because the website - fmovies.se has alot of great content.

Thanks for your help,
DC

**Comment by pranav-prakash** [comment]
It works fine for me. Once you click play on the movie and click on the extension you will see two icons: a download button and a cast button. Click on the cast button and it should work.

**Comment by crystal90** [comment]
When you say 'click on the extension' do you mean the icon on the toolbar?
I don't see any buttons after I click on the icon.

Thanks, DC

**Comment by pranav-prakash** [comment]
![image](https://cloud.githubusercontent.com/assets/10335022/22910408/a7a1a1a4-f20e-11e6-8ba1-c9ae2bb33bc1.png)

Once you click the icon in the toolbar you will see a popup like this.

**Comment by crystal90** [comment]
OK, I didn't see the download arrow and cast icon when the cursor wasn't
over the popup. I got it to work now.

Thanks so much for your help,
DC
