### ISSUE TITLE
RokuCast stopped working

### ISSUE THREAD

**Issue by alinamalina21** [pranav-prakash/RokuCast#25]
Hi @pranav-prakash 

First and foremost, thank you SO much for developing this extension, really! 

That said, i'd like to report an issue. During the last 2-3 weeks, everytime I click the Chrome icon to cast a compatible video to Roku, the RokuCast screen opens in the TV, but then it takes me back to Roku's Home page. The video won't even load in the TV.
Could you please take a look into it?

My Google Chrome version is 58.0.3029.110 (64-bit) and my Roku version is 7.6.0 build 4125-09.
Thank you so much!

**Comment by pranav-prakash** [comment]
Which video are you trying to cast? I'll try to see if I can replicate the issue on my end.

**Comment by pranav-prakash** [comment]
Interesting, the user [here](https://github.com/pranav-prakash/RokuCast/issues/24) had almost the same issue. Roku must have changed something in an update, because this seems to be a relatively recent issue. For some reason this doesn't seem to affect my roku 2xs (which might make sense if it's a software update related issue).

The fix that worked for the above user was to switch to the version of RokuCast in the master branch (https://github.com/pranav-prakash/RokuCast/tree/master). The version there uses a separate companion app that you sideload to the roku. I've included instructions on how to install it in the README file, but let me know if any steps or unclear or more info is needed.

**Comment by alinamalina21** [comment]
Thanks, @pranav-prakash. I'll give it a try later today.

**Comment by alinamalina21** [comment]
Hi @pranav-prakash,
I gave it a try today according to the instructions and it's a bit worse now, since my Roku became completely unresponsive to the extension. 

I sucessfully installed the extension from the unzipped folder (I have removed the previous installed extension previously) and entered my IP address. Nothing happened on my Roku. My extension seemed to work and I was even able to download the video, but no casting happened.
After that, I uninstalled the unzipped extension and reinstalled the one from Chrome app store, and nothing happened on my Roku again. I repeated the processes twice again, and my Roku kept unresponsive. 

Any thoughts? Sorry for the hassle.
Regards,
Alina

**Comment by pranav-prakash** [comment]
Did you also sideload the companion app on the roku? Unless I'm misreading, you seem to have only installed the chrome extension from the `master` branch. In addition to the chrome extension, it also  requires a separate app to be installed the roku. I'll copy paste the instructions for installing the app below:

>To install the Roku app you need to enable development mode on your Roku box (follow online instructions for that). To then sideload the app, first zip the contents of the RokuCast Receiver folder (found inside the [master](https://github.com/pranav-prakash/RokuCast/tree/master) branch) (so go into the folder, control-A to select the three items, right click and zip it). Then upload that zip file to the Roku. 

After that you can then install the extension from that branch and it should hopefully work.


------

Also, you mentioned that you "reinstalled the one from Chrome app store" — I haven't personally published this extension on the chrome store. It appears you are referring to [this one](https://chrome.google.com/webstore/detail/rokucast/colepknnmkjpnooobdflkniegcfgaahg) which someone else has uploaded. I don't have any problem with this, just letting you know that it wasn't published by me and might not be the latest code. Also I did a diff and it looks identical to what is on my github so it should be safe, but I cannot be certain that the uploader might not add something bad in a sneaky update - just a slight note of caution.
