### ISSUE TITLE
detecting Roku devices on network via MAC address

### ISSUE THREAD

**Issue by sonofagl1tch** [pranav-prakash/RokuCast#30]
I saw in the readme that you are looking to add auto detection of roku devices into the application. I do this by filtering my local arp table to any devices with MAC addresses that start with "88:DE:A9". This is the vendor OUI code for all current Roku devices according to [wireshark](https://www.wireshark.org/tools/oui-lookup.html).

MAC Address/OUI | Vendor {Company}
-- | --
88:DE:A9 | Roku, Inc.

**Comment by yaelsprikut** [comment]
@sonofagl1tch so is B0:EE:7B
