### ISSUE TITLE
Cannot save the IP: no save button

### ISSUE THREAD

**Issue by degarb** [pranav-prakash/RokuCast#31]
I can enter the ip.  But, hitting enter/return does nothing.  And no save button.

Chrome Version 63.0.3239.132

**Comment by degarb** [comment]
Is there a file I can edit, since the java code isn't compatible with modern Chrome?

**Comment by degarb** [comment]
I tried regedit and browsing C:\Users\User_Name\AppData\Local\Google\Chrome\User Data\Default\Extensions  but cannot find the file to edit to manually put in the ip address for roku.

Again, the code is not working on chrome-extension://cehckiamakjgmfdllobmgfamlffblhdg/options.html

**Comment by pranav-prakash** [comment]
Hm what do you mean there's no save button? The code runs fine on my browser.

if you want to manually edit background.js

**Comment by degarb** [comment]
I cloned and downloaded.  Looked different, more complete, than the
downloaded zip.

Should check the distribution zip.  I am one of the many unfamiliar with
how get hub works. But been downloading zips since the 90s.

**Comment by pranav-prakash** [comment]
Ok so does it work now then?

**Comment by degarb** [comment]
Well, at first it didn't with clone and downloaded version, then it did. I
am holding my breath the submit button doesn't disappear, since my roku ip
floats around.

Best regards, Dennis Garber

Mobile voice transcription a courtesy of Google Inc.-- causing accidents
since 2008 to make way for the Google driverless car of the future. .

**Comment by pranav-prakash** [comment]
You can assign your roku a static ip in router preferences

**Comment by degarb** [comment]
I wish. But, just combed through all settings; and, they missed that one. I
can only mac address filter.

Roku 2, I don't believe has ability either.

I would buy another router. But found most routers beak after one year. So,
will stick with this one until it breaks.

I would consider switching if throttling and better, total parental
control. Likely not features an open source firmware would endorse. Even
then, just amazed this unit hasn't broken in 1 year, unlike 3 previous
routers.

Best regards, Dennis Garber

Mobile voice transcription a courtesy of Google Inc.-- causing accidents
since 2008 to make way for the Google driverless car of the future.

**Comment by pranav-prakash** [comment]
This guy had the same issue as you:

https://github.com/pranav-prakash/RokuCast/issues/32

I now understand what the problem was -- change the ip using the settings cog in the bottom right corner when you click on the extension, not using the options page provided by chrome.
