### ISSUE TITLE
Issue entering IP address

### ISSUE THREAD

**Issue by waltspence** [pranav-prakash/RokuCast#32]
The option box doesn't accept the input for the roku ip address. There is no submit button and enter doesn't retain the address in the field.

Edit: There is one in the settings cog but not under the options page in the extensions.

![image](https://user-images.githubusercontent.com/328087/35273633-3c7a0404-0007-11e8-9d9f-d5b4b7fc5794.png)

![image](https://user-images.githubusercontent.com/328087/35273653-5237b412-0007-11e8-9da7-f2a98f1dd19f.png)

**Comment by pranav-prakash** [comment]
Yeah use the one in the setings cog.
