### ISSUE TITLE
RokuCast activates, doesn't work -- has taken over my PC Display Settings and won't give it back. 

### ISSUE THREAD

**Issue by JoeParez** [pranav-prakash/RokuCast#33]
I tried to use RokuCast but unfortunately it never functioned. I used to be able to cast my PC (Windows 10) to my Roku using the Display settings. Now for some reason, out of nowhere RokuCast opens, after a few months of trying to get it to work and nothing happens. I don't want to try and make it work, I'd like to cast from the display settings of my PC. I have even deleted Rokucast from my computer and browser and have done a factory reset on the Roku and still when I connect via the Disply settings on Windows 10, RokuCast shows up and does nothing. I would like to go back to my old settings but am dumbfounded.

**Comment by pranav-prakash** [comment]
What you are seeing/want to use is the native roku desktop casting functionality (also known as Miracast). It has nothing to do with this extension. Miracast is notoriously finicky and that is why it probably does not work.

**Comment by JoeParez** [comment]
Hey Pranav..

Thank you for responding.
Any idea how restore the miracast? I am a little over my head here.

**Comment by pranav-prakash** [comment]
As I mentioned Miracast is native to roku and is not touched by this extension at all. There is nothing to restore.
