### ISSUE TITLE
New RokuCast or copy?

### ISSUE THREAD

**Issue by nitrocode** [pranav-prakash/RokuCast#39]
https://chrome.google.com/webstore/detail/rokucast/colepknnmkjpnooobdflkniegcfgaahg?hl=en

@pranav-prakash Is that you? or is that a separate extension with the same name?

**Comment by pranav-prakash** [comment]
Not mine.

**Comment by nitrocode** [comment]
@pranav-prakash it's an exact copy of your code. You should consider putting a license in this repo cause http://shadikabajah.com/ definitely ripped off your code and claimed it as his own...

**Comment by pranav-prakash** [comment]
Meh it's too much of a hassle to DMCA and I don't really care too much. It's also probably more accessible to the general public as a published extension.

I did a quick glance of the code and it seems safe (in that nothing was added that scrapes browser history/other badware).

**Comment by nitrocode** [comment]
Wow. It got taken down immediately.

**Comment by pranav-prakash** [comment]
Wow that's surprising. I've reported actual browser-history-stealing-extensions that are somehow still up. /shrug
