### ISSUE TITLE
RokuCast not working anymore?

### ISSUE THREAD

**Issue by 4LAU** [pranav-prakash/RokuCast#41]
Error message: Refused to load the script 'https://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' because it violates the following Content Security Policy directive: "script-src 'self' http://localhost:9008 https://www.google-analytics.com".

**Comment by pranav-prakash** [comment]
From the looks of it, it seems to be some sort of CSP related thing (although I'm not having any issue). I've updated the extension. Can you try again now.

**Comment by jcrew876** [comment]
Same here now i cannot even save my ip address... i enter my address and hit save if i go to try again it is empty? any help?

**Comment by jcrew876** [comment]
tried updating and all

**Comment by 4LAU** [comment]
Works for me now - am able to save the IP address as well. Thank you! Will report back with any problems.

**Comment by pranav-prakash** [comment]
Glad to hear.
