### ISSUE TITLE
Live streaming HTML 5 / MP4 video will not cast to Roku 

### ISSUE THREAD

**Issue by Uptown007** [pranav-prakash/RokuCast#42]
I cannot cast live streaming from chrome tab to rokucast. 

Here is the URL to source: 
<video data-html5-video="" preload="metadata" src="blob:http://mlbhdstreams.xyz/960b0dfd-5703-4cf8-83db-c64de0e15396"><style class="clappr-style">[data-html5-video]

Details from chrome extension: 
Description
Cast HTML5 Videos to your Roku
Version
0.1.11
Size
1.1 MB
ID
cjfdphkgelmjolmoigbgljgiifidadgi

Thoughts?

**Comment by pranav-prakash** [comment]
Live streaming video is unlikely to work due to Roku's format limitations as well as the non-standard manner in which livestreams are often encoded
