### ISSUE TITLE
Unable to Install RokuCast Receiver

### ISSUE THREAD

**Issue by BananaManCJ** [pranav-prakash/RokuCast#48]
When I try to upload the RokuCast Receiver.zip file to my Roku, it says "Install Failure: No manifest. Invalid package." I'm pretty sure this is because in the Required Attributes section of https://sdkdocs.roku.com/display/sdkdoc/Roku+Channel+Manifest page, it says you need to have the attributes "splash_screen_hd" and "splash_screen_sd," which are not in the current manifest.

**Comment by pranav-prakash** [comment]
Hm are you sure you are zipping the *contents* of the RokuCast receiver folder? You should create your zip file by selecting the 3 items `images`, `source`, `manifest`, and zipping those (i.e. not zipping the containing folder itself).

Also, is there a particular reason you have opted to use the version that requires the separate roku receiver? The [main playOnRoku branch](https://github.com/pranav-prakash/RokuCast) does not require any receiver to be sideloaded to the roku and only requires the chrome extension. I'd recommend just using that unless you have a particular need to spoof user-agent.

**Comment by BananaManCJ** [comment]
I just think having the video history feature of the receiver channel would be useful for me.

**Comment by pranav-prakash** [comment]
Ah ok makes sense. Note that a lot of times video URLs generated by CDNs are ephemeral (they are uniquely generated and expire after 1 day or so) so past video URLs are not guaranteed to resolve.

**Comment by BananaManCJ** [comment]
Would it be very hard to update the receiver to be able to run on current Roku's?

**Comment by pranav-prakash** [comment]
Are you sure you zipped the files properly? The error you described seems to indicate that it couldn't find the manifest which makes me think that you may have zipped the folder instead of zipping the contents of the folder.

Regarding the `splash_screen_hd`: I don't believe that not including those would lead to the error you indicated.

**Comment by BananaManCJ** [comment]
Thanks, that worked!
