### ISSUE TITLE
"Play On Roku" as an alternative to the custom channel

### ISSUE THREAD

**Issue by DrewML** [pranav-prakash/RokuCast#7]
Hey!

To start with, thank you for the work on this extension! I was very happy to find it.

I wanted to point out that you could eliminate the necessity to maintain your own Roku channel for this. The Roku team actually includes a channel built in ("Play On Roku") that developers can use to play video content, without having to create a separate channel. It can be accessed on Roku 2+ devices.

An example post to the device would be:

```
/input/15985?t=v&u=https://14-lvl3-gcs-pdl.vimeocdn.com/vimeo-prod-skyfire-std-us/01/278/6/151394301/464549211.mp4?expires=1452986239&token=01e6cb04e5a360356311f&k=http://yourhostnamehere.com/splash-roku.png&videoName=https://14-lvl3-gcs-pdl.vimeocdn.com/vimeo-prod-skyfire-std-us/01/278/6/151394301/464549211.mp4?expires=1452986239&token=01e6cb04e5a360356311f&videoFormat=mp4
```

Parameters:
**u** - URI of the video
**videoName** - Name to display on the Roku device for the video
**k** - URI to an image to use as a loading screen

It _looks_ like all you might have to do is make a modification [here](https://github.com/pranav-prakash/RokuCast/blob/Production/RokuCast/background.js#L23)

This is the method that the [Connect SDK](https://github.com/ConnectSDK) uses to play videos on Roku.

**Comment by pranav-prakash** [comment]
Wow nice find — I'll update the code and readme when I get a chance.

Cheers!

**Comment by Amandysha** [comment]
Amazing! @DrewML I love what you just suggested. Thank you very much. :clap::clap::clap:

**Comment by Amandysha** [comment]
@pranav-prakash  Btw, any plan to update extension to support HLS Streaming (M3U8)? It will be great! :raised_hands: :raised_hands:

**Comment by pranav-prakash** [comment]
@Amandysha Yes I just added it. Do you have any sample videos to test with?

**Comment by Amandysha** [comment]
I try from this link (http://www.gravlab.com/2013/10/26/example-sample-http-live-streaming-m3u8-embedded-player/) with mp4 and m3u8 media. Mp4 work fine but m3u8 dont work.

**Comment by TheDoctorsLife** [comment]
Any update on this?

**Comment by pranav-prakash** [comment]
https://github.com/pranav-prakash/RokuCast/tree/playOnRoku

Try that branch out. Since we removed the need for companion app, the extension should be all you need.

**Comment by pranav-prakash** [comment]
@TheDoctorsLife 

https://github.com/pranav-prakash/RokuCast/tree/playOnRoku

Try that branch out. Since we removed the need for companion app, the extension should be all you need.

If it works well, I can probably just make that the main branch. You do lose the ability to see cast history though, but I guess that's an acceptable tradeoff.
